name: Jonathan
favicon: null
layout_spectrum: 0.01753268134780228
typography_spectrum: 0.34126913151703775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9734329089988023
  lightness: 0.84187246626243
  saturation: 0.9659125797916204
  rhythmicContrast: 0.6225397903472185
purpose: []
